imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        types:
            Geography:      CrEOF\Spatial\DBAL\Types\GeographyType
            Point:          CrEOF\Spatial\DBAL\Types\Geography\PointType
            Linestring:     CrEOF\Spatial\DBAL\Types\Geography\LineStringType
            Polygon:        CrEOF\Spatial\DBAL\Types\Geography\PolygonType
            MultiPolygon:   CrEOF\Spatial\DBAL\Types\Geography\PolygonType
            jsonb:          BDGS\DatabaseModelBundle\Types\DBAL\JsonbArrayType
            Pointz:         BDGS\DatabaseModelBundle\Types\DBAL\PointzType
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                server_version: 9.4
                charset:  UTF8
                mapping_types:
                    _text:          string
                    geometry:       string
                    Point:          Point
                    Linestring:     Linestring
                    Polygon:        Polygon
                    MultiPolygon:   MultiPolygon
                    Geography:      Geography
                    jsonb:          jsonb

    orm:
        # naming_strategy:        doctrine.orm.naming_strategy.underscore
        default_entity_manager: default
        # auto_generate_proxy_classes: "%kernel.debug%"
        # auto_mapping: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection:     default
                mappings:
                    AppBundle:  ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# DunglasJsonLdApi configuration
dunglas_api:
    title:       "%api_name%"
    description: "%api_description%"

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:  ["%cors_allow_origin%"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers: ["content-type", "authorization"]
        max_age:       3600
    paths:
        '^/': ~

# Nelmio API Doc
nelmio_api_doc:
    sandbox:
        accept_type:        "application/json"
        body_format:
            formats:        [ "json" ]
            default_format: "json"
        request_format:
            formats:
                json:       "application/json"
