# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    resource.agency:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Agency" ]
        tags:      [ { name: "api.resource" } ]

    resource.unit:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Unit" ]
        tags:      [ { name: "api.resource" } ]

    resource.contact:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Contact" ]
        tags:      [ { name: "api.resource" } ]

    resource.contact_station:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\ContactStation" ]
        tags:      [ { name: "api.resource" } ]

    resource.instrument:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Instrument" ]
        tags:      [ { name: "api.resource" } ]

    resource.itrf:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Itrf" ]
        calls:
            - method: "initPluralizedName"
              arguments: [ 'Itrfs' ]
        tags:      [ { name: "api.resource" } ]

    resource.mail:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Mail" ]
        tags:      [ { name: "api.resource" } ]

    resource.plate_model:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\PlateModel" ]
        tags:      [ { name: "api.resource" } ]

    resource.country:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Country" ]
        tags:      [ { name: "api.resource" } ]

    resource.photograph:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Photograph" ]
        tags:      [ { name: "api.resource" } ]

    resource.plate:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Plate" ]
        tags:      [ { name: "api.resource" } ]

    resource.sitelog_plate:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\SitelogPlate" ]
        tags:      [ { name: "api.resource" } ]

    resource.reference_point:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\ReferencePoint" ]
        tags:      [ { name: "api.resource" } ]

    resource.report:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Report" ]
        tags:      [ { name: "api.resource" } ]

    resource.solution:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Solution" ]
        tags:      [ { name: "api.resource" } ]

    resource.site:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Site" ]
        tags:      [ { name: "api.resource" } ]

    resource.station:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Station" ]
        tags:      [ { name: "api.resource" } ]

##################################################################

    resource.cumulated_residual:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\CumulatedResidual" ]
        tags:      [ { name: "api.resource" } ]

    resource.covariance:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Covariance" ]
        tags:      [ { name: "api.resource" } ]

    resource.solution:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Solution" ]
        tags:      [ { name: "api.resource" } ]

    resource.plate_rotation_pole:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\PlateRotationPole" ]
        tags:      [ { name: "api.resource" } ]

    resource.soln:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Soln" ]
        tags:      [ { name: "api.resource" } ]

    resource.transformation:
        parent:     "api.resource"
        arguments: [ "AppBundle\\Entity\\Transformation" ]
        tags:      [ { name: "api.resource" } ]